--- Scripts para API REPORTES 

-- Crear tabla en la base de datos [Api_ReporteDb]

CREATE TABLE [Api_ReporteDb].[dbo].AUDITORIA_REPORTES (
	REPORTE_ID INT IDENTITY(1,1) PRIMARY KEY,
	NRO_SOLICITUD VARCHAR(50),
	NRO_REPORTE VARCHAR(25),
	ESTADO VARCHAR(1),
	INTENTOS_GENERAR INT DEFAULT 0,
	USANDOSE VARCHAR(1),
	INFORMADO_EMAIL VARCHAR(1) DEFAULT 0,
	TIEMPO_GENERACION DECIMAL,
	NOMBRE_PDF VARCHAR(255),
	FECHA_INGRESO DATETIME DEFAULT CURRENT_TIMESTAMP,
	FECHA_PROCESADO DATETIME,
	FECHA_EN_CARPETA DATETIME,
	API_BODY NVARCHAR(max),
	FECHA_ELIMINADO_SERVIDOR DATETIME
)

select * from [Api_ReporteDb].[dbo].AUDITORIA_REPORTES   order by FECHA_INGRESO desc

--- QUERY PARA SALVAR SOLICITUDES SIN REPORTE PORQUE FUERON APROBADAS PERO NO DESEMBOLSADAS EL DIA DE PASO A PRODUCCION

INSERT INTO [Api_ReporteDb].[dbo].AUDITORIA_REPORTES (NRO_SOLICITUD, NRO_REPORTE, ESTADO, USANDOSE, INTENTOS_GENERAR, API_BODY)
SELECT C5000, 3546, 0, 0, 0, '{"parametros":["Solicitud=' + CAST(C5000 AS VARCHAR(50)) + '"],"numeroReporte":"3546","idTipoDoc":"20"}'
FROM [172.22.2.211].[FDLM].[dbo].[SL_SolicitudCredito]
LEFT JOIN [172.22.2.211].[FDLM].[dbo].[SL_SolicitudDesembolsos] ON SL_SolicitudDesembolsos.NUMSOLICITUD = SL_SolicitudCredito.C5000 AND SL_SolicitudDesembolsos.ESTADO = 'D'
WHERE (C5063 = 'AP' OR C5063 = 'CV') 
      AND SL_SolicitudCredito.tz_lock = 0
	  AND (SL_SolicitudDesembolsos.tz_lock = 0 OR SL_SolicitudDesembolsos.tz_lock IS NULL)
      AND (SL_SolicitudDesembolsos.NUMSOLICITUD IS NULL OR SL_SolicitudDesembolsos.ESTADO = 'R')
      AND CodCarpeta NOT IN ('') 
      AND C5008 NOT IN (461, 462) 
      AND Operativa != '1614' 
      AND C5005 IN (0, 1)
ORDER BY C5006 DESC
